language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "dmeiners88-github"
    token:
      secure: "VPzNttVHxMcARrqQ2+2pU/PSFg9G5+Kv5kzTX8SZ8OE6MTGGJe2MBSn5myZkAHaEh9AORBjznTZ5V6THMkHGuPr6pZKIWzRSrH+SOjOPyZ1GoJhze6UA56jIs0FKH+3zUsOp9aSGECflhsQb6jOQy2+ihJUDCo7jj2D6jmXDuJ70BOLRZlrA5ruzbOXxRqoAtUmJ+ovHek+LtJwMH7Ox5KL820CVKFHXeSzSTNPWtR7CvEXiRy95/AlbUvLI99OBklANgXVZmjWVnbItord2urKmvY7oecXc8aKTRTsWGmWnW3Ur9F8cxiADG4yMg6vNVNbITWiT7FGW83rnoNTryQC79vLISGyEDk+9w2CwC5B+jsMq5aUkSTHDmTAxJORaL1GYDqaqSN1rqIi5Tx6tx5Pp6WWwYnapQdsYv5X1rAi5RoxsV4Mnzo1rRWfrYmeFpLajapRC0hm4IpecCJKD+346wsFIXbQ1t2n4LKa6GblLAgbSvn/++eL40Om1jx4QBQlk6K2/mJNKR4N7BLm1pvuugQYlUJ/TYjMnvdqrIbMsmYHVAiZDRJUUJBI4VANFHgZS+aEyHzA8mEnTnscBeSuKj77b3L9SIZtPs0+w9d+rXVchVXbqicoh5nNKM0rspeJdRmXu4g3PsQaZK5dGyTgQDIGebatnscjVHBH4EXI="
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'